# BUILD_LIB = ./lib
# --build-lib=$(BUILD_LIB)

all:
	python3 setup.py build_ext --inplace

clean:
	rm -rf build \
	em2d/*.cpp \
	em2d/laser/*.cpp \
	em2d/udist/*.cpp \
	em2d/density/*.cpp \
	em2d/filter/*.cpp \
	em2d/*.so em2d/em2d/*.so


